[application]
name = "srvr"
default_platform = "fullstack"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "TRMNL Dashboard"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
