services:
  srvr:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    init: true
    volumes:
      - .:/app
      - bash-history:/home/dev/.bash_history_dir
    ports:
      - "8080:8080"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    command:
      "sleep infinity"
  srvr-published:
    profiles: ["published"]
    build:
      context: .
      dockerfile: Dockerfile
      target: publish
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - srvr-data:/data
    init: true
    ports:
      - "80:8080"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - DATABASE_URL=sqlite:///data/data.db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--enable-feature=promql-experimental-functions"

volumes:
  bash-history:
  prometheus-data:
  srvr-data:
